settings:
  output_dir: "./logs/"
  save_model: True
  save_positions: True
  debug_level: DEBUG
  telemetry: False

# TODO make this section optional
actions:
    available_actions:
      simple:

# TODO To be removed
agent:
  cartpole:
    camera_params:
      witdh: 640
      height: 480

environments:
  simple:
    env_name: CartPole-v0
    environment_folder: cartpole
    runs: 20000
    update_every: 10000

inference:
  qlearn:
    inference_file: /home/ruben/Desktop/my-RL-Studio/rl_studio/logs/qlearn_models/1_20220718_0010_act_set_simple_epsilon_0.01_QTABLE.pkl
    actions_file: /home/ruben/Desktop/my-RL-Studio/rl_studio/logs/qlearn_models/actions_set_20220718_0010
  dqn:
    inference_file: /home/ruben/Escritorio/my-Rl-Studio/rl_studio/logs/dqn_models/1_20220813_1305_act_set_simple_epsilon_1_QTABLE.pkl

algorithm:
    qlearn:
      alpha: 0.85
      epsilon: 0.99
      gamma: 0.95
      epsilon_discount: 0.99999998

    dqn:
      gamma: 0.95
      epsilon_discount: 0.9998

    sarsa:
